# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherStoryboard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherStoryboard
  pod 'MaterialComponents/BottomSheet'

  target 'WeatherStoryboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherStoryboardUITests' do
    # Pods for testing
  end

end
